# PCF settings
PCF_TARGET_URL: api.run.pivotal.io
PCF_DOMAIN: cfapps.io
PCF_USERNAME: jwilliams@pivotal.io
PCF_PASSWORD: 144Theroad#
PCF_ORG: Southeast
PCF_SPACE: jwilliams
APP_NAME: attendees-regions