resources:
  - name: pcf-ers-demo
    type: git
    source:
      uri: https://github.com/jwilliams-pivotal/pcf-ers-demo.git
      branch: master

  - name: stage-pcf-ers-demo
    type: cf
    source:
      api: https://api.local2.pcfdev.io
      username: admin
      password: admin
      organization: pcfdev-org
      space: pcfdev-space
      skip_cert_check: true

jobs:
  - name: pcf-ers-demo
    plan:
    - get: pcf-ers-demo
      trigger: true
    - task: package
      file: pcf-ers-demo/concourse/tasks/package.yml
    - put: stage-pcf-ers-demo
      params:
        manifest: pcf-ers-demo/manifest.yml


