resources:
  - name: source-code
    type: git
    source:
      uri: https://github.com/jwilliams-pivotal/pcf-ers-demo
      branch: master

  - name: stage-pcf
    type: cf
    source:
      api: https://api.local2.pcfdev.io
      username: admin
      password: admin
      organization: pcfdev-org
      space: pcfdev-space
      skip_cert_check: true

jobs:
  - name: deploy
    plan:
    - get: source-code
    - task: package
      file: source-code/concourse/tasks/package.yml
    - put: stage-pcf
      params:
        manifest: source-code/manifest.yml
        path: output/pcf-ers-demo.jar

  - name: zero-downtime-deploy
    plan:
    - get: source-code
    - task: package
      file: source-code/concourse/tasks/package.yml
    - task: zero-downtime-deploy
      file: source-code/concourse/tasks/zero-downtime-push.yml
