resources:
  - name: pcf-ers-demo
    type: git
    source:
      uri: https://github.com/jwilliams-pivotal/pcf-ers-demo
      branch: master

jobs:
  - name: test
    plan:
    - get: pcf-ers-demo
      trigger: true
    - task: test
      file: pcf-ers-demo/concourse/tasks/test.yml

  - name: package
    plan:
    - get: pcf-ers-demo
      trigger: true
      passed: [test]
    - task: package
      file: pcf-ers-demo/concourse/tasks/package.yml

  - name: zero-downtime-deploy
    plan:
    - get: pcf-ers-demo
      trigger: true
      passed: [package]
    - task: package
      file: pcf-ers-demo/concourse/tasks/package.yml
    - task: zero-downtime-deploy
      file: pcf-ers-demo/concourse/tasks/zero-downtime-push.yml
