resources:
  - name: gh-release-1.0
    type: github-release
    source:
      user: jwilliams-pivotal
      repository: pcf-ers-demo
      version: 1.0
      cache: false
  - name: gh-release-2.0
      type: github-release
      source:
        user: jwilliams-pivotal
        repository: pcf-ers-demo
        version: 2.0
        cache: false

  - name: stage-pcf
    type: cf
    source:
      api: https://api.local2.pcfdev.io
      username: admin
      password: admin
      organization: pcfdev-org
      space: pcfdev-space
      skip_cert_check: true

jobs:
  - name: deploy-1.0
    plan:
    - get: gh-release-1.0
    - put: stage-pcf
      params:
        manifest: gh-release-1.0/manifest.yml
        path: gh-release-1.0/pcf-ers-demo.jar
  - name: deploy-2.0
    plan:
    - get: gh-release-2.0
    - put: stage-pcf
      params:
        manifest: gh-release-2.0/manifest.yml
        path: gh-release-2.0/pcf-ers-demo.jar
