resources:
  - name: pcf-ers-demo
    type: git
    source:
      uri: https://github.com/jwilliams-pivotal/pcf-ers-demo.git
      branch: master

  - name: pcf-settings
    type: cf
    source:
      api: https://api.local2.pcfdev.io
      username: admin
      password: admin
      organization: pcfdev-org
      space: pcfdev-space
      skip_cert_check: true

jobs:
  - name: package
    plan:
    - get: pcf-ers-demo
      trigger: true
    - task: package
      privileged: true
      file: pcf-ers-demo/concourse/tasks/package.yml
    params:
      cache: true

  - name: deploy
    plan:
    - get: pcf-ers-demo
      trigger: true
      passed: [package]
    - put: pcf-settings
      params:
        manifest: pcf-ers-demo/manifest.yml
        path: build-output/pcf-ers-demo-0.0.1-SNAPSHOT.jar


