resources:
  - name: gh-release-1.x
    type: github-release
    source:
      user: jwilliams-pivotal
      repository: pcf-ers-demo

  - name: gh-release-2.x
    type: github-release
    source:
      user: jwilliams-pivotal
      repository: pcf-ers-demo

  - name: stage-pcf
    type: cf
    source:
      api: https://api.local2.pcfdev.io
      username: admin
      password: admin
      organization: pcfdev-org
      space: pcfdev-space
      skip_cert_check: true

jobs:
  - name: deploy-1.x
    plan:
    - get: gh-release-1.x
      version:
        in:
        tag: v1.0.0
    - put: stage-pcf
      params:
        manifest: gh-release-1.x/manifest.yml
        path: gh-release-1.x/pcf-ers-demo.jar

  - name: deploy-2.x
    plan:
    - get: gh-release-2.x
      version:
        in:
        tag: v2.0.0
    - put: stage-pcf
      params:
        manifest: gh-release-2.x/manifest.yml
        path: gh-release-2.x/pcf-ers-demo.jar
