resources:
  - name: pcf-ers-demo
    type: git
    source:
      uri: https://github.com/jwilliams-pivotal/pcf-ers-demo
      branch: master

  - name: pcf-ers-demo-canary
    type: git
    source:
      uri: https://github.com/jwilliams-pivotal/pcf-ers-demo
      branch: master

  - name: deployment-scripts
    type: git
    source:
      uri: https://github.com/jwilliams-pivotal/pcf-ers-demo
      branch: master

  - name: pcf-ers-demo-releases
    type: github-release
    source:
      user: jwilliams-pivotal
      repository: pcf-ers-demo

jobs:
  - name: test
    plan:
    - get: pcf-ers-demo
      trigger: true
    - task: test
      file: pcf-ers-demo/concourse/tasks/test.yml

  - name: zero-downtime-deploy
    plan:
    - get: pcf-ers-demo
      trigger: true
      passed: [test]
    - task: zero-downtime-deploy
      params:
        PCF_TARGET_URL: {{PCF_TARGET_URL}}
        PCF_USERNAME: {{PCF_USERNAME}}
        PCF_PASSWORD: {{PCF_PASSWORD}}
        PCF_ORG: {{PCF_ORG}}
        PCF_SPACE: {{PCF_SPACE}}
      privileged: true
      file: pcf-ers-demo/concourse/tasks/zero-downtime-push.yml

  - name: deploy-A-and-B
    plan:
    - aggregate:
      - get: deployment-scripts
      - get: pcf-ers-demo-releases
        version:
          in:
          tag: v1.0.0-AB
    - task: deploy-ab
      params:
        PCF_TARGET_URL: {{PCF_TARGET_URL}}
        PCF_USERNAME: {{PCF_USERNAME}}
        PCF_PASSWORD: {{PCF_PASSWORD}}
        PCF_ORG: {{PCF_ORG}}
        PCF_SPACE: {{PCF_SPACE}}
      file: deployment-scripts/concourse/tasks/ab-push.yml

  - name: unittest-canary
    plan:
    - get: pcf-ers-demo-canary
    - task: unittest-canary
      file: pcf-ers-demo-canary/concourse/tasks/canary-test.yml

  - name: deploy-canary
    plan:
    - get: pcf-ers-demo-canary
      trigger: true
      passed: [unittest-canary]
    - task: canary-deploy
      params:
        PCF_TARGET_URL: {{PCF_TARGET_URL}}
        PCF_USERNAME: {{PCF_USERNAME}}
        PCF_PASSWORD: {{PCF_PASSWORD}}
        PCF_ORG: {{PCF_ORG}}
        PCF_SPACE: {{PCF_SPACE}}
      privileged: true
      file: pcf-ers-demo-canary/concourse/tasks/canary-push.yml

  - name: uat-canary
    plan:
    - get: pcf-ers-demo-canary
      trigger: true
      passed: [deploy-canary]
    - task: uattest-canary
      file: pcf-ers-demo-canary/concourse/tasks/canary-uattest.yml
      on_success:
        task: scale-canary
        params:
          PCF_TARGET_URL: {{PCF_TARGET_URL}}
          PCF_USERNAME: {{PCF_USERNAME}}
          PCF_PASSWORD: {{PCF_PASSWORD}}
          PCF_ORG: {{PCF_ORG}}
          PCF_SPACE: {{PCF_SPACE}}
        file: pcf-ers-demo-canary/concourse/tasks/canary-scale.yml
      on_failure:
        task: canary-rollback
        params:
          PCF_TARGET_URL: {{PCF_TARGET_URL}}
          PCF_USERNAME: {{PCF_USERNAME}}
          PCF_PASSWORD: {{PCF_PASSWORD}}
          PCF_ORG: {{PCF_ORG}}
          PCF_SPACE: {{PCF_SPACE}}
        file: pcf-ers-demo-canary/concourse/tasks/canary-rollback.yml