resources:
  - name: pcf-ers-demo
    type: git
    source:
      uri: https://github.com/jwilliams-pivotal/pcf-ers-demo
      branch: master

  - name: pcf-ers-demo-releases
    type: github-release
    source:
      user: jwilliams-pivotal
      repository: pcf-ers-demo

jobs:
  - name: test
    plan:
    - get: pcf-ers-demo
      trigger: true
    - task: test
      file: pcf-ers-demo/concourse/tasks/test.yml

  - name: package
    plan:
    - get: pcf-ers-demo
      trigger: true
      passed: [test]
    - task: package
      file: pcf-ers-demo/concourse/tasks/package.yml

  - name: zero-downtime-deploy
    plan:
    - get: pcf-ers-demo
      trigger: true
      passed: [package]
    - task: package
      file: pcf-ers-demo/concourse/tasks/package.yml
    - task: zero-downtime-deploy
      file: pcf-ers-demo/concourse/tasks/zero-downtime-push.yml

  - name: deploy-ab
    plan:
    - aggregate:
      - get: pcf-ers-demo
      - get: pcf-ers-demo-releases
        version:
          in:
          tag: v1.0.0-AB
    - task: deploy-ab
      file: pcf-ers-demo/concourse/tasks/ab-push.yml


