platform: linux

image_resource:
  type: docker-image
  source:
    repository: williamsjt/cloudfoundry
    tag: latest

run:
  path: sh
  args:
  - -exc
  - |
    cf login -a https://api.local2.pcfdev.io --skip-ssl-validation -u admin -p admin -o pcfdev-org -s pcfdev-space
    cf push attendees-a -f pcf-ers-demo-releases/manifest.yml -p pcf-ers-demo-a.jar
    cf map-route attendees-a local2.pcfdev.io --hostname attendees-ab
    cf push attendees-b -f pcf-ers-demo-releases/manifest.yml -p pcf-ers-demo-b.jar
    cf map-route attendees-b local2.pcfdev.io --hostname attendees-ab