platform: linux

image_resource:
  type: docker-image
  source:
    repository: williamsjt/cloudfoundry
    tag: latest

inputs:
  - name: pcf-ers-demo-releases

run:
  path: sh
  args:
  - -exc
  - |
    cf login -a https://api.local.pcfdev.io --skip-ssl-validation -u admin -p admin -o pcfdev-org -s pcfdev-space
    cf push attendees-a -f pcf-ers-demo-releases/manifest.yml -p pcf-ers-demo-releases/pcf-ers-demo-A.jar
    cf map-route attendees-a local.pcfdev.io --hostname attendees-ab
    cf push attendees-b -f pcf-ers-demo-releases/manifest.yml -p pcf-ers-demo-releases/pcf-ers-demo-B.jar
    cf map-route attendees-b local.pcfdev.io --hostname attendees-ab