platform: linux

image_resource:
  type: docker-image
  source:
    repository: williamsjt/cloudfoundry
    tag: latest

inputs:
  - name: pcf-ers-demo-canary

run:
  path: sh
  args:
  - -exc
  - |
    pcf-ers-demo-canary/mvnw -f pcf-ers-demo-canary/pom.xml package

params:
  MAVEN_BASEDIR: pcf-ers-demo-canary