platform: linux

image_resource:
  type: docker-image
  source:
    repository: williamsjt/cloudfoundry
    tag: latest

inputs:
  - name: pcf-ers-demo

run:
  path: sh
  args:
  - -exc
  - |
    test_url=http://attendees-canary.local2.pcfdev.io/basics2
    urlstatus=$(curl -o /dev/null --silent --head --write-out '%{http_code}' ${test_url})
    code=200
    if [ $urlstatus ne $code ]
    then
      exit 1
    fi