platform: linux

image_resource:
  type: docker-image
  source:
    repository: williamsjt/cloudfoundry
    tag: latest

inputs:
  - name: pcf-ers-demo

run:
  path: sh
  args:
  - -exc
  - |
    newman run pcf-ers-demo/concourse/UAT_pcf-ers-demo.postman_collection