platform: linux

image_resource:
  type: docker-image
  source:
    repository: williamsjt/cloudfoundry
    tag: latest

inputs:
  - name: source-code

outputs:
  - name: output

run:
  path: "source-code/concourse/scripts/package.sh"

params:
  MAVEN_BASEDIR: source-code
