platform: linux

image_resource:
  type: docker-image
  source:
    repository: williamsjt/cloudfoundry
    tag: latest

inputs:
  - name: pcf-ers-demo

outputs:
  - name: output

run:
  path: "source-code/concourse/scripts/package.sh"
