platform: linux

image_resource:
  type: docker-image
  source:
    repository: openjdk
    tag: latest

inputs:
  - name: pcf-ers-demo

outputs:
  - name: jar-file
    path: output/target/

run:
  path: "pcf-ers-demo/mvnw"
  args: ["-f", "pcf-ers-demo/pom.xml", "package"]

params:
  MAVEN_BASEDIR: pcf-ers-demo
