platform: linux

image_resource:
  type: docker-image
  source:
    repository: openjdk
    tag: latest

inputs:
  - name: pcf-ers-demo

outputs:
  - name: output/target

run:
  path: "pcf-ers-demo/mvnw"
  args: ["-f", "pcf-ers-demo/pom.xml", "package"]

run:
  path: "cp"
  args: ["-R","./target", "output/target"]

params:
  MAVEN_BASEDIR: pcf-ers-demo
