platform: linux

image_resource:
  type: docker-image
  source:
    repository: openjdk
    tag: latest

inputs:
  - name: pcf-ers-demo
    path: .

run:
  path: "./mvnw"
  args: ["-f", "./pom.xml", "package"]

