platform: linux

image_resource:
  type: docker-image
  source:
    repository: williamsjt/cloudfoundry
    tag: latest

inputs:
  - name: pcf-ers-demo

outputs:
  - name: output

run:
  path: sh
  args:
  - -exc
  - |
    pcf-ers-demo/mvnw -f pcf-ers-demo/pom.xml package
    cp pcf-ers-demo/target/*.jar ./output
    cp pcf-ers-demo/manifest.yml ./output

params:
  MAVEN_BASEDIR: pcf-ers-demo
