platform: linux

image_resource:
  type: docker-image
  source:
    repository: williamsjt/cloudfoundry
    tag: latest

inputs:
  - name: pcf-ers-demo

run:
  path: "pcf-ers-demo/mvnw"
  args: ["-f", "pcf-ers-demo/pom.xml", "test"]

params:
  MAVEN_BASEDIR: pcf-ers-demo
