platform: linux

image_resource:
  type: docker-image
  source:
    repository: williamsjt/cloudfoundry
    tag: latest

inputs:
  - name: output

run:
  path: sh
  args:
  - -exc
  - |
    cf login -a https://api.local2.pcfdev.io --skip-ssl-validation -u admin -p admin -o pcfdev-org -s pcfdev-space
    cf zero-downtime-push attendees -f output/manifest.yml -p output/pcf-ers-demo.jar