platform: linux

image_resource:
  type: docker-image
  source:
    repository: williamsjt/cloudfoundry
    tag: latest

inputs:
  - name: pcf-ers-demo

run:
  path: sh
  args:
  - -exc
  - |
    pcf-ers-demo/mvnw -f pcf-ers-demo/pom.xml package -DskipTests=true
    cf login -a https://api.local2.pcfdev.io --skip-ssl-validation -u admin -p admin -o pcfdev-org -s pcfdev-space
    cf zero-downtime-push attendees -f pcf-ers-demo/manifest.yml -p target/pcf-ers-demo.jar

params:
  MAVEN_BASEDIR: pcf-ers-demo