spring.profiles.active: dev

spring.jpa.hibernate.ddl-auto: update

ribbon:
  eureka:
   enabled: false

spring:
  application:
    name: attendees
    
# Using macros that are replaced by maven build
info:
  build:
    artifact: pcf-ers-demo
    name: @project.name@
    description: @project.description@
    version: 0.0.1-SNAPSHOT